name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to use"
        required: true
        type: environment

jobs:
  Build:
    runs-on: ["ubuntu-latest"]
    steps:
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.ref }}"
      - uses: actions/checkout@v6
      - run: tree
  Test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: Build
    environment: Test
    steps:
      - run: 'echo "Testing..."'
  Load-Test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: Build
    environment: Load-Test
    steps:
      - run: 'echo "Testing..."'
      - uses: juliangruber/sleep-action@v2.0.3
        with:
          # A time period as ms or string (100, 10s, 1m)
          time: 15s
  Production:
    if: github.event_name == 'workflow_dispatch' && inputs.environment == 'Production'
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment: Production
    env:
      URL: https://writeabout.net
    steps:
      - run: 'echo "Step 1 deploying..."'
      - run: 'echo "Step 2 deploying..."'
      - run: 'echo "Step 3 deploying..."'
      - run: 'echo "Step 4 deploying..."'
      - run: 'echo "Step 5 deploying..."'
       
    
